# Generated by Django 3.0.7 on 2020-06-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='gen',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
